### ISSUE TITLE
您好，我想问一下数据持久化保存数据的问题

### ISSUE THREAD

**Issue by cbyzzy** [quickmsg/smqtt#11]
我注意到关联了数据库后（我用的是mysql），发送的消息如果带retain，那么是可以保存到数据库的。我想问一下如果是不带retain的消息，目前的框架内有办法能将数据保存到数据库中么？或者保存到内存通过外部接口获取到这个数据么？
多谢。

**Comment by 1ssqq1lxr** [comment]
已解决
