### ISSUE TITLE
OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3724541959, max: 3739746304)

### ISSUE THREAD

**Issue by sjshare** [quickmsg/smqtt#20]
MQTT客户端按照每秒100条发送数据到服务端，正常接收一个多小时后服务端报错。

![image](https://user-images.githubusercontent.com/19381444/185909879-e085843b-ad2d-4665-8df9-d2794d96a14c.png)

**Comment by 1ssqq1lxr** [comment]
2.0最近发布，修复内存泄露问题！



---Original---
From: ***@***.***&gt;
Date: Mon, Aug 22, 2022 19:24 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [quickmsg/smqtt] OutOfDirectMemoryError: failed to allocate 16777216byte(s) of direct memory (used: 3724541959, max: 3739746304) (Issue #20)




 
MQTT客户端按照每秒100条发送数据到服务端，正常接收一个多小时后服务端报错。
