### ISSUE TITLE
拦截器问题

### ISSUE THREAD

**Issue by a007007007csy** [quickmsg/smqtt#4]
1.ConnectionCounterInterceptor类根据CONNECT拦截，但ChannelRegistry.counts()执行通常发生在registry()之前，所以得到的count不是最新的。 
2.尝试通过CONNACK拦截进行计数，发现CONNACK拦截不成功

**Comment by 1ssqq1lxr** [comment]
ConnectionCounterInterceptor是我提供的一个demo类 在下个版本里会被去掉（拦截器下个版本改动比较大）
如果你需要获取连接数，下个版本我提供了http接口去获取连接数据（包含链接信息）。

**Comment by 1ssqq1lxr** [comment]
目前的代码更新在 release/1.0.6 有兴趣参与我项目 可以加我微信 17512575402！

**Comment by 1ssqq1lxr** [comment]
目前的代码更新在 release/1.0.6 有兴趣参与我项目 可以加我微信 17512575402！
