### ISSUE TITLE
maven打包ui模块失败

### ISSUE THREAD

**Issue by sxh-netizen** [quickmsg/smqtt#5]
当我进行maven打包的时候 出现了以下错误
![image](https://user-images.githubusercontent.com/58098910/125264415-6cead300-e336-11eb-9311-0b96473b0ab8.png)
maven版本3.5.2   idea版本2020.2

**Comment by 1ssqq1lxr** [comment]
- 先安装node && npm
- 进入smqtt-ui目录npm install
