### ISSUE TITLE
mqtt over websocket的8999的端口如何连接？

### ISSUE THREAD

**Issue by aboluo-gy** [quickmsg/smqtt#6]
大佬您好，1883mqtt的可以连接发送消息，mqtt over websocket 的有什么客户端可以测试么？网上找的mqtt over websocket连接界面，可以连接其他人的mqtt over websocket，连接123.57.69.210:8999的会失败，请问知道是哪块配置错了吗？或者这块有什么注意事项或者推荐吗

**Comment by 1ssqq1lxr** [comment]
添加一下微信交流群吧！

**Comment by 1ssqq1lxr** [comment]
这个是不是你的是/mqtt 需要设置下这个smqtt.websocket.path

**Comment by aboluo-gy** [comment]
> 添加一下微信交流群吧！

在群里了

**Comment by aboluo-gy** [comment]
连接上了
